### ISSUE TITLE
Better colors for light theme

### ISSUE THREAD

**Issue by Bengt** [richrace/highlight-selected#26]
The highlights for light themes are very harsh and dark making it hard to read highlighted text. Using the quite popular [Fizzy theme](https://atom.io/themes/fizzy), I ended up with this:

``` less
.editor {
  // Box
  .highlight-selected .region {
    border-color: #ddd;
  }
  // Background
  .highlight-selected.background .region {
    background-color: rgba(155, 149, 0, 0.1);
  }
  // Light theme box (set in settings)
  .highlight-selected.light-theme .region {
    border-color: rgba(255, 128, 64, 0.4);
  }
  // Light theme background (set in settings)
  .highlight-selected.light-theme.background .region {
    background-color: rgba(255, 128, 64, 0.2);
  }
}
```
