### ISSUE TITLE
Not closing the bottom/top of the highlight on line 144/145

### ISSUE THREAD

**Issue by dionisiusma** [richrace/highlight-selected#84]
I first noticed the issue while coding in PHP, but I just tested it on plain text and the errors persists.

STR: just put a lot of text in a file and selected/highlight some word on the line 144 and look for problems on the bottom border of the highlight. If everything is okay, check the top border of a selected word on the line 145. See image below:

![atombug](https://cloud.githubusercontent.com/assets/12850001/8210204/e4170552-14de-11e5-9ae4-02664cad653c.png)

ER: Bottom border closing the rectangle.

**Comment by richrace** [comment]
Yea, I've seen this recently. Just had a quick look. It's basically a CSS issue. I need to update the following:

```less
.highlight-selected .region {
      border-radius: 2px;
      box-sizing: content-box;
      padding: 0 1px 0 0;
      margin: -1px 0 0 -1px;
      background-color: transparent;
      border-width: 1px;
      border-style: solid;
    }
```

to:

```less
.highlight-selected .region {
      // Maybe make this 3px (be the same as find-and-replace package
      border-radius: 2px; 
      box-sizing: border-box;
      background-color: transparent;
      border-width: 1px;
      border-style: solid;
    }
```
